const targetWords = [
  "everything is better with you!",
  "we hate the lausd bitch",
  "A person's mood can also be influenced by LSD.",
  "let us see the probability you seeing me on tv",
  "belilah doomer",
  "by way of community college",
  "",
  "call me a good girl and i'll be all yours",
  "loveland, colorado",
  "i'll break you when i see you again",
  "i love you",
  "",
  "",
  "pinning you down and making you mine",
  "",
  "you make me so happy",
  "",
  "choke me harder",
  "",
  "i want to treat you better in every way",
  "do you want to see my boobs?",
  "did you like my boobs?",
  "well, i love you",
  "she foia on my records till i release everything under pressure",
  "kiss me harder ^-^",
  "Spooky season takes over DPMHS",
  "THE BESTEST GIRLFRIEND EVER",
  "the prettiest rose in the garden",
  "the promenade shops at centerra",
  "",
  "all i want is you",
  "roygbiv",
  "kiss kiss fall in love",
  "make every day a good day",
  "it's giving positive vibes",
  "whore",
  "stunningly beautiful and gorgeous beyond compare",
  "late night talker",
  "silly subby delilah",
  "delilah, delilah, delilah, delilah delilah",
  "",
  "i'd let you drink from my cup if you're ever thirsty",
  "pink lemonade",
  "absolutely positively gorgeous",
  "what a yapper",
  "spanking, hair pulling, pinning you down roughly",
  "delilah rose, how does your garden grow?",
  "",
  "ur so kissable ehe",
  "",
  "i need you to pin you badly",
  "mark my body with your love",
  "seal the deal 🦭",
  "let me lose myself with you",
  "do you wanna go inside your room",
  "",
  "im pregnant",
  "you're such a slut",
  "no hints here!",
  "do the bdsm test",
  "i want you"
];

export default targetWords;
