const targetWords = [
  "everything is better with you",
  "i love being with you",
  "you make my heart happy",
  "you are my sunshine",
  "you make me smile",
  "you are my favorite person",
  "you light up my life",
  "you are the best part of my day",
  "you complete me",
  "you are my happy place",
  "you make my heart sing",
  "you are my reason to smile",
  "you are my world",
  "you make every day brighter",
  "you are my dream come true",
  "you are the love of my life",
  "you make me a better person",
  "you are my everything",
  "you bring joy to my life",
  "you are my greatest adventure",
  "you are the light in my darkness",
  "you make my heart skip a beat",
  "you are my forever",
  "you are my soulmate",
  "you make every moment special",
  "you are the reason I believe in love",
  "you are my greatest blessing",
  "you make me feel alive",
  "you are my safe haven",
  "you are the melody to my song",
  "you are my inspiration",
  "you make my dreams come true",
  "you are my partner in crime",
  "you are the peanut butter to my jelly",
  "you are my favorite hello and hardest goodbye",
  "you are the apple of my eye",
  "you make my heart flutter",
  "you are my sunshine on a rainy day",
  "you are the missing piece to my puzzle",
  "you make every moment count",
  "you are the reason I wake up smiling",
  "you are my greatest treasure",
  "you make me feel cherished",
  "you are the spark in my life",
  "you make every day an adventure",
  "you are my comfort zone",
  "you make me feel special",
  "you are the reason I am happy",
  "you are my favorite distraction",
  "you make my heart pound",
  "you are my greatest joy",
  "you make me feel loved",
  "you are the sunshine in my soul",
  "you are my happy ending",
  "you make every day worth living",
  "you are the reason I smile",
];

export default targetWords;
